#!/usr/bin/env node
// Builds ONE self-contained preview page: preview/design-system-preview.html
//  - runs the token build (dist/)
//  - generates src/preview/registry.generated.ts from every src/components/*/*.stories.tsx
//  - bundles the preview app + components with esbuild (CSS Modules), React mapped to window.React from a CDN
//  - inlines tokens, CSS and JS into the HTML. Only React/ReactDOM and the Atkinson font load from the web.
// Usage: node scripts/build-preview.mjs [--copy <dir>]
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, copyFileSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'

const root = resolve('.')
const argv = process.argv.slice(2)
const copyTo = argv.includes('--copy') ? argv[argv.indexOf('--copy') + 1] : null
const ESB = process.env.ESBUILD_PATH || '/usr/local/lib/node_modules_global/lib/node_modules/tsx/node_modules/esbuild'
const esbuild = createRequire(import.meta.url)(ESB)

execFileSync('node', ['scripts/build-tokens.mjs', '.'], { stdio: 'inherit' })

// ---- registry ----
// components only
const scan = (rel) => {
  const dir = join(root, rel)
  if (!existsSync(dir)) return []
  return readdirSync(dir).filter((d) => !d.startsWith('.') && statSync(join(dir, d)).isDirectory()).sort().flatMap((d) => {
    const f = readdirSync(join(dir, d)).find((x) => x === `${d}.stories.tsx`) || readdirSync(join(dir, d)).find((x) => x.endsWith('.stories.tsx'))
    return f ? [{ folder: d, file: f, base: rel.replace(/^src\//, '') }] : []
  })
}
const entries = [...scan('src/components')] // pages (src/pages) are not in the gallery
const reg = [
  '// generated by scripts/build-preview.mjs. Do not edit.',
  ...entries.map((e, i) => `import * as s${i} from '../${e.base}/${e.folder}/${e.file.replace(/\.tsx$/, '')}'`),
  'export interface RegistryEntry { folder: string; mod: Record<string, unknown> }',
  `export const REGISTRY: RegistryEntry[] = [${entries.map((e, i) => `{ folder: '${e.folder}', mod: s${i} as unknown as Record<string, unknown> }`).join(', ')}]`,
].join('\n')
writeFileSync(join(root, 'src/preview/registry.generated.ts'), reg + '\n')

// ---- bundle ----
const globals = {
  name: 'react-globals',
  setup(b) {
    b.onResolve({ filter: /^react(-dom)?(\/.*)?$/ }, (a) => ({ path: a.path, namespace: 'rg' }))
    b.onLoad({ filter: /.*/, namespace: 'rg' }, (a) => {
      if (a.path === 'react') return { contents: 'module.exports = window.React', loader: 'js' }
      if (a.path === 'react-dom' || a.path === 'react-dom/client') return { contents: 'module.exports = window.ReactDOM', loader: 'js' }
      if (a.path === 'react/jsx-runtime' || a.path === 'react/jsx-dev-runtime') return {
        loader: 'js',
        contents: `const R = window.React
          const make = (type, props, key) => { const { children, ...rest } = props || {}; if (key !== undefined) rest.key = key
            return Array.isArray(children) ? R.createElement(type, rest, ...children) : children === undefined ? R.createElement(type, rest) : R.createElement(type, rest, children) }
          export const jsx = make, jsxs = make, jsxDEV = make, Fragment = R.Fragment`,
      }
      return { contents: 'module.exports = {}', loader: 'js' }
    })
    // type-only / tooling packages never reach the browser
    b.onResolve({ filter: /^@(storybook|figma)\// }, (a) => ({ path: a.path, namespace: 'empty' }))
    b.onLoad({ filter: /.*/, namespace: 'empty' }, () => ({ contents: 'module.exports = {}', loader: 'js' }))
  },
}
const result = await esbuild.build({
  entryPoints: [join(root, 'src/preview/main.tsx')], bundle: true, write: false, outdir: join(root, 'dist/preview-bundle'),
  format: 'iife', platform: 'browser', target: 'es2020', jsx: 'automatic', minify: true, legalComments: 'none',
  loader: { '.module.css': 'local-css', '.css': 'css' },
  define: { 'process.env.NODE_ENV': '"production"' },
  plugins: [globals], logLevel: 'warning',
})
const js = result.outputFiles.find((f) => f.path.endsWith('.js')).text
execFileSync('node', ['scripts/build-modes.mjs', '.'], { stdio: 'inherit' })
// modes.css goes last so [data-theme]/[data-density] overrides win over :root token definitions
const css = (result.outputFiles.find((f) => f.path.endsWith('.css'))?.text || '') + '\n' + readFileSync(join(root, 'dist/modes.css'), 'utf8')

// ---- html ----
const tokens = JSON.parse(readFileSync(join(root, 'dist/tokens.json'), 'utf8'))
const gaps = JSON.parse(readFileSync(join(root, 'dist/gaps.json'), 'utf8'))
const state = JSON.parse(readFileSync(join(root, 'design-system-state.json'), 'utf8'))
execFileSync('node', ['scripts/lean-tokens.mjs', '.'], { stdio: 'inherit' })
const passMap = JSON.parse(readFileSync(join(root, 'dist/lean/passthrough.json'), 'utf8'))
const lean = Object.entries(tokens).filter(([, t]) => passMap[t.cssVar]).map(([n]) => n)
const data = { tokens, gaps, state, lean, builtAt: new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Los_Angeles', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23', timeZoneName: 'short' }).format(new Date()).replace(',', '') }
const miniReact = readFileSync(join(root, 'src/preview/mini-react.js'), 'utf8')
const safe = (s) => s.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--')
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>6sense design system preview</title>
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible+Next:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<noscript>This preview needs JavaScript.</noscript>
<script id="ds-data" type="application/json">${safe(JSON.stringify(data))}</script>
<pre id="boot-error" hidden style="white-space:pre-wrap;padding:16px;color:#b00020;font:12px monospace"></pre>
<script>window.addEventListener('error',function(e){var el=document.getElementById('boot-error');if(el){el.hidden=false;el.textContent+=(e.message||e.error)+'\\n'}})</script>
<script>${safe(miniReact)}</script>
<script>${safe(js)}</script>
</body>
</html>
`
mkdirSync(join(root, 'preview'), { recursive: true })
const outFile = join(root, 'preview/design-system-preview.html')
writeFileSync(outFile, html)
console.log(`Preview built: ${outFile} (${(html.length / 1024).toFixed(0)} KB, ${entries.length} components, ${Object.keys(tokens).length} tokens)`)
if (copyTo) { mkdirSync(resolve(copyTo), { recursive: true }); copyFileSync(outFile, join(resolve(copyTo), 'design-system-preview.html')); console.log(`Copied to ${copyTo}`) }
