#!/usr/bin/env node
// Generates src/index.ts (public exports) and fails on duplicate export names across components.
import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { createRequire } from 'node:module'
const root = resolve('.')
const esb = createRequire(import.meta.url)(process.env.ESBUILD_PATH || '/usr/local/lib/node_modules_global/lib/node_modules/tsx/node_modules/esbuild')
const dir = join(root, 'src/components')
const names = readdirSync(dir).filter((x) => !x.startsWith('.') && statSync(join(dir, x)).isDirectory()).sort()
const seen = {}; let dup = 0
for (const d of names) {
  const r = await esb.build({ entryPoints: [join(dir, d, 'index.ts')], bundle: true, write: false, format: 'esm', metafile: true, jsx: 'automatic', loader: { '.module.css': 'local-css', '.css': 'css' }, external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client'], outdir: '/tmp/x', logLevel: 'silent' })
  const out = Object.values(r.metafile.outputs).find((o) => o.entryPoint)
  for (const e of out.exports) { if (seen[e] && seen[e] !== d) { console.error(`Duplicate export ${e}: ${seen[e]} and ${d}`); dup++ } seen[e] = d }
}
const body = [
  "// generated by scripts/gen-index.mjs. Do not edit.",
  "import './styles/tokens.css'",
  "import './styles/reset.css'",
  "import './styles/focus.css'",
  "export * from './primitives'",
  "export * from './icons'",
  ...names.map((n) => `export * from './components/${n}'`),
].join('\n') + '\n'
writeFileSync(join(root, 'src/index.ts'), body)
console.log(`src/index.ts: ${names.length} components, ${Object.keys(seen).length} exports, ${dup} duplicates`)
process.exit(dup ? 1 : 0)
