// generated by scripts/build-mui-theme.mjs from the token JSON. Do not edit.
export const SIXDS_THEME = {
  "light": {
    "primary": "#2A696F",
    "primaryDark": "#214D50",
    "inverse": "#F3F7F6",
    "secondary": "#DAE7E3",
    "error": "#913030",
    "errorDark": "#541C1C",
    "success": "#0C7D45",
    "warning": "#995D0F",
    "info": "#34585B",
    "textPrimary": "#063236",
    "textSecondary": "#34585B",
    "textDisabled": "#668284",
    "border": "#063236",
    "focus": "#0C47A7",
    "page": "#F3F7F6",
    "card": "#F8FAF9"
  },
  "dark": {
    "primary": "#59CCD9",
    "primaryDark": "#73DCE7",
    "inverse": "#063236",
    "secondary": "#1A5258",
    "error": "#EE8C8C",
    "errorDark": "#F7B6B6",
    "success": "#12E27A",
    "warning": "#F3A949",
    "info": "#C8DAD4",
    "textPrimary": "#F8FAF9",
    "textSecondary": "#DAE7E3",
    "textDisabled": "#668284",
    "border": "#F3F7F6",
    "focus": "#A5BFE9",
    "page": "#042A2E",
    "card": "#0A3A3F"
  },
  "opacityDivider": 0.16,
  "fontFamily": "\"Atkinson Hyperlegible Next\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif",
  "radius": {
    "control": 12,
    "small": 4,
    "surface": 16
  },
  "control": {
    "medium": 40,
    "small": 32
  },
  "spacingUnit": 8,
  "typography": {
    "heading.1": {
      "fontSize": "1.728rem",
      "fontWeight": 600,
      "lineHeight": 1.2
    },
    "heading.2": {
      "fontSize": "1.44rem",
      "fontWeight": 600,
      "lineHeight": 1.2
    },
    "heading.3": {
      "fontSize": "1.2rem",
      "fontWeight": 600,
      "lineHeight": 1.2
    },
    "heading.4": {
      "fontSize": "1rem",
      "fontWeight": 600,
      "lineHeight": 1.5
    },
    "paragraph.1": {
      "fontSize": "1rem",
      "fontWeight": 400,
      "lineHeight": 1.5
    },
    "paragraph.2": {
      "fontSize": "0.833rem",
      "fontWeight": 400,
      "lineHeight": 1.5
    },
    "help.1": {
      "fontSize": "0.833rem",
      "fontWeight": 400,
      "lineHeight": 1.5
    },
    "button.1": {
      "fontSize": "0.833rem",
      "fontWeight": 500,
      "lineHeight": 1.2
    },
    "label.1": {
      "fontSize": "0.833rem",
      "fontWeight": 600,
      "lineHeight": 1.5
    }
  },
  "density": {
    "compact": {
      "space": 0.75,
      "control": 0.8
    },
    "default": {
      "space": 1,
      "control": 1
    },
    "spacious": {
      "space": 1.25,
      "control": 1.2
    }
  }
} as const
