// GENERATED by scripts/gen-chart-palette.mjs from tokens/primitive/color.json. Do not edit by hand.
// Chart colors are 6DS colors only. Re-run `npm run gen:chart-palette` after changing tokens.
export interface PaletteStep { token: string; step: string; hex: string; contrast: number }
export const HUES = ["teal","blue","green","amber","red","ink"] as const
export type Hue = (typeof HUES)[number]
export const PRIMARY_HUE: Hue = "teal"
export const MIN_CONTRAST = 3
/** Usable steps per hue (>= 3:1 on white), light to dark. */
export const USABLE: Record<Hue, readonly PaletteStep[]> = {
  "teal": [
    {
      "token": "core.color.teal.500",
      "step": "500",
      "hex": "#3c9faa",
      "contrast": 3.12
    },
    {
      "token": "core.color.teal.600",
      "step": "600",
      "hex": "#35848d",
      "contrast": 4.34
    },
    {
      "token": "core.color.teal.700",
      "step": "700",
      "hex": "#2a696f",
      "contrast": 6.27
    },
    {
      "token": "core.color.teal.800",
      "step": "800",
      "hex": "#275e63",
      "contrast": 7.32
    },
    {
      "token": "core.color.teal.900",
      "step": "900",
      "hex": "#214d50",
      "contrast": 9.37
    }
  ],
  "blue": [
    {
      "token": "core.color.blue.400",
      "step": "400",
      "hex": "#3e74cc",
      "contrast": 4.59
    },
    {
      "token": "core.color.blue.500",
      "step": "500",
      "hex": "#205fc5",
      "contrast": 5.99
    },
    {
      "token": "core.color.blue.600",
      "step": "600",
      "hex": "#0c47a7",
      "contrast": 8.49
    },
    {
      "token": "core.color.blue.700",
      "step": "700",
      "hex": "#0a3376",
      "contrast": 12.01
    }
  ],
  "green": [
    {
      "token": "core.color.green.500",
      "step": "500",
      "hex": "#109e57",
      "contrast": 3.47
    },
    {
      "token": "core.color.green.600",
      "step": "600",
      "hex": "#0c7d45",
      "contrast": 5.2
    },
    {
      "token": "core.color.green.700",
      "step": "700",
      "hex": "#0b6538",
      "contrast": 7.16
    },
    {
      "token": "core.color.green.800",
      "step": "800",
      "hex": "#0a522e",
      "contrast": 9.3
    },
    {
      "token": "core.color.green.900",
      "step": "900",
      "hex": "#093e24",
      "contrast": 12.17
    }
  ],
  "amber": [
    {
      "token": "core.color.amber.500",
      "step": "500",
      "hex": "#c37713",
      "contrast": 3.52
    },
    {
      "token": "core.color.amber.600",
      "step": "600",
      "hex": "#995d0f",
      "contrast": 5.35
    },
    {
      "token": "core.color.amber.700",
      "step": "700",
      "hex": "#7c4c0e",
      "contrast": 7.25
    },
    {
      "token": "core.color.amber.800",
      "step": "800",
      "hex": "#68410d",
      "contrast": 8.93
    },
    {
      "token": "core.color.amber.900",
      "step": "900",
      "hex": "#50320b",
      "contrast": 11.65
    }
  ],
  "red": [
    {
      "token": "core.color.red.300",
      "step": "300",
      "hex": "#d35a5a",
      "contrast": 3.9
    },
    {
      "token": "core.color.red.400",
      "step": "400",
      "hex": "#c84141",
      "contrast": 4.9
    },
    {
      "token": "core.color.red.500",
      "step": "500",
      "hex": "#ac3939",
      "contrast": 6.18
    },
    {
      "token": "core.color.red.600",
      "step": "600",
      "hex": "#913030",
      "contrast": 7.87
    },
    {
      "token": "core.color.red.700",
      "step": "700",
      "hex": "#742525",
      "contrast": 10.32
    },
    {
      "token": "core.color.red.800",
      "step": "800",
      "hex": "#672222",
      "contrast": 11.48
    },
    {
      "token": "core.color.red.900",
      "step": "900",
      "hex": "#541c1c",
      "contrast": 13.46
    }
  ],
  "ink": [
    {
      "token": "core.color.ink.600",
      "step": "600",
      "hex": "#668284",
      "contrast": 4.12
    },
    {
      "token": "core.color.ink.700",
      "step": "700",
      "hex": "#4a6b6d",
      "contrast": 5.81
    },
    {
      "token": "core.color.ink.800",
      "step": "800",
      "hex": "#34585b",
      "contrast": 7.8
    },
    {
      "token": "core.color.ink.900",
      "step": "900",
      "hex": "#063236",
      "contrast": 13.84
    }
  ]
}
export const CATEGORICAL_STEPS: readonly (PaletteStep & { hue: Hue })[] = [
  {
    "token": "core.color.blue.500",
    "step": "500",
    "hex": "#205fc5",
    "contrast": 5.99,
    "hue": "blue"
  },
  {
    "token": "core.color.amber.600",
    "step": "600",
    "hex": "#995d0f",
    "contrast": 5.35,
    "hue": "amber"
  },
  {
    "token": "core.color.teal.600",
    "step": "600",
    "hex": "#35848d",
    "contrast": 4.34,
    "hue": "teal"
  },
  {
    "token": "core.color.red.500",
    "step": "500",
    "hex": "#ac3939",
    "contrast": 6.18,
    "hue": "red"
  },
  {
    "token": "core.color.green.600",
    "step": "600",
    "hex": "#0c7d45",
    "contrast": 5.2,
    "hue": "green"
  },
  {
    "token": "core.color.blue.400",
    "step": "400",
    "hex": "#3e74cc",
    "contrast": 4.59,
    "hue": "blue"
  },
  {
    "token": "core.color.amber.500",
    "step": "500",
    "hex": "#c37713",
    "contrast": 3.52,
    "hue": "amber"
  },
  {
    "token": "core.color.teal.500",
    "step": "500",
    "hex": "#3c9faa",
    "contrast": 3.12,
    "hue": "teal"
  },
  {
    "token": "core.color.red.300",
    "step": "300",
    "hex": "#d35a5a",
    "contrast": 3.9,
    "hue": "red"
  },
  {
    "token": "core.color.green.500",
    "step": "500",
    "hex": "#109e57",
    "contrast": 3.47,
    "hue": "green"
  },
  {
    "token": "core.color.blue.600",
    "step": "600",
    "hex": "#0c47a7",
    "contrast": 8.49,
    "hue": "blue"
  },
  {
    "token": "core.color.amber.700",
    "step": "700",
    "hex": "#7c4c0e",
    "contrast": 7.25,
    "hue": "amber"
  },
  {
    "token": "core.color.teal.700",
    "step": "700",
    "hex": "#2a696f",
    "contrast": 6.27,
    "hue": "teal"
  },
  {
    "token": "core.color.red.700",
    "step": "700",
    "hex": "#742525",
    "contrast": 10.32,
    "hue": "red"
  },
  {
    "token": "core.color.green.700",
    "step": "700",
    "hex": "#0b6538",
    "contrast": 7.16,
    "hue": "green"
  }
]
export const OTHER_STEP: PaletteStep = {"token":"core.color.ink.800","step":"800","hex":"#34585b","contrast":7.8}
export const INK_TEXT = {"token":"core.color.ink.900","hex":"#063236"}
export const WHITE = {"token":"core.color.white","hex":"#ffffff"}
