#!/usr/bin/env node
// Builds dist/modes.css (dark theme + density) from tokens/modes/*.json. Source token JSON is not touched.
//  - validates that every overridden token exists and every alias resolves
//  - checks WCAG AA contrast for the pairs listed in dark.json (exit 1 on failure)
//  - emits:  :root[data-theme="dark"] { ... }   and   :root[data-density="compact"|"spacious"] { ... }
// Run after build-tokens. Usage: node scripts/build-modes.mjs [root]
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(process.argv[2] || '.')
const tokens = JSON.parse(readFileSync(join(root, 'dist/tokens.json'), 'utf8'))
const dark = JSON.parse(readFileSync(join(root, 'tokens/modes/dark.json'), 'utf8'))
const dens = JSON.parse(readFileSync(join(root, 'tokens/modes/density.json'), 'utf8'))
const cssVar = (n) => '--' + n.replace(/\./g, '-')
const errors = []

const ext = Object.fromEntries(Object.entries(dark.extend).filter(([k]) => !k.startsWith('$')))
const known = (n) => tokens[n] || ext[n] !== undefined
const resolveAlias = (str) => str.replace(/\{([^}]+)\}/g, (m, ref) => { if (!known(ref)) { errors.push(`unknown alias ${ref}`); return m } return `var(${cssVar(ref)})` })

const darkLines = []
for (const [n, hex] of Object.entries(ext)) { if (!/^#[0-9a-fA-F]{6}$/.test(hex)) errors.push(`extend ${n}: not a 6-digit hex`); darkLines.push(`  ${cssVar(n)}: ${hex};`) }
const overrides = Object.entries(dark.override)
for (const [n, v] of overrides) {
  if (!tokens[n]) { errors.push(`override ${n}: no such token`); continue }
  if (tokens[n].layer === 'primitive') errors.push(`override ${n}: primitives are not themed. Override a semantic token`)
  darkLines.push(`  ${cssVar(n)}: ${resolveAlias(v)};`)
}

// ---- contrast ----
const hexOf = (n, seen = new Set()) => {
  if (ext[n]) return ext[n]
  const t = tokens[n]; if (!t) return null
  const ov = dark.override[n]
  if (ov) { const m = ov.match(/^\{([^}]+)\}$/); return m ? hexOf(m[1], seen) : null }
  if (/^#/.test(t.value)) return t.value
  if (t.aliases?.length === 1 && !seen.has(n)) { seen.add(n); return hexOf(t.aliases[0], seen) }
  return null
}
const lum = (hex) => { const h = hex.replace('#', ''); const c = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).map((x) => (x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4)); return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2] }
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05) }
const report = []
for (const [kind, fg, bg] of dark.contrast.pairs) {
  const f = hexOf(fg), b = hexOf(bg)
  if (!f || !b) { report.push({ kind, fg, bg, ratio: null, note: 'not a solid color (gradient or composed), check by eye' }); continue }
  const r = ratio(f, b), need = kind === 'text' ? 4.5 : 3
  report.push({ kind, fg, bg, fgHex: f, bgHex: b, ratio: +r.toFixed(2), need, pass: r >= need })
}
const failed = report.filter((r) => r.pass === false)

if (errors.length) { console.error('Mode build failed:\n- ' + [...new Set(errors)].join('\n- ')); process.exit(1) }

let css = `/* generated by scripts/build-modes.mjs. Do not edit. DRAFT dark theme and density modes. */\n:root[data-theme="dark"] {\n  color-scheme: dark;\n${darkLines.join('\n')}\n}\n`
for (const [mode, map] of Object.entries(dens.modes)) {
  const lines = Object.entries(map).map(([n, v]) => { if (!tokens[n]) errors.push(`density ${mode}: no such token ${n}`); return `  ${cssVar(n)}: ${v};` })
  css += `:root[data-density="${mode}"] {\n${lines.join('\n')}\n}\n`
}
if (errors.length) { console.error('Mode build failed:\n- ' + errors.join('\n- ')); process.exit(1) }
writeFileSync(join(root, 'dist/modes.css'), css)
writeFileSync(join(root, 'dist/modes.json'), JSON.stringify({ dark: { extend: ext, override: dark.override }, density: dens.modes, contrast: report }, null, 2))
console.log(`Modes built: dark ${overrides.length} overrides + ${Object.keys(ext).length} draft steps, density ${Object.keys(dens.modes).join('/')}. Contrast ${report.filter((r) => r.pass).length}/${report.filter((r) => r.ratio !== null).length} pairs pass.`)
if (failed.length) { for (const f of failed) console.error(`  FAIL ${f.kind} ${f.fg} on ${f.bg}: ${f.ratio}:1 (needs ${f.need})  ${f.fgHex} / ${f.bgHex}`); process.exit(1) }
