#!/usr/bin/env node
// Builds ONE standalone page (no preview shell, no token editor, no component gallery): just the page, its CSS and the tokens.
//   node scripts/build-page.mjs IntegrationSettings "<output dir>" [--theme dark] [--density compact|spacious]
// Output: <output dir>/<kebab-name>.html (self-contained, works offline). Uses the library components from src/components.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'

const root = resolve('.')
const [name, outArg, ...rest] = process.argv.slice(2)
if (!name || !outArg) { console.error('Usage: node scripts/build-page.mjs <PageFolder> <output dir> [--theme dark] [--density compact|spacious]'); process.exit(1) }
const flag = (n) => (rest.includes(n) ? rest[rest.indexOf(n) + 1] : null)
const theme = flag('--theme') || 'light', density = flag('--density') || 'default'
const pageDir = join(root, 'src/pages', name)
if (!existsSync(pageDir)) { console.error(`No page folder ${pageDir}`); process.exit(1) }
const ESB = process.env.ESBUILD_PATH || '/usr/local/lib/node_modules_global/lib/node_modules/tsx/node_modules/esbuild'
const esbuild = createRequire(import.meta.url)(ESB)

execFileSync('node', ['scripts/build-tokens.mjs', '.'], { stdio: 'inherit' })
execFileSync('node', ['scripts/build-modes.mjs', '.'], { stdio: 'inherit' })

const entry = join(pageDir, 'standalone.generated.tsx')
writeFileSync(entry, `// generated by scripts/build-page.mjs. Do not edit.
import { createRoot } from 'react-dom/client'
import '../../styles/index.css'
import { ${name} } from './${name}'
createRoot(document.getElementById('root')!).render(<${name} />)
`)
const globals = {
  name: 'react-globals',
  setup(b) {
    b.onResolve({ filter: /^react(-dom)?(\/.*)?$/ }, (a) => ({ path: a.path, namespace: 'rg' }))
    b.onLoad({ filter: /.*/, namespace: 'rg' }, (a) => {
      if (a.path === 'react') return { contents: 'module.exports = window.React', loader: 'js' }
      if (a.path === 'react-dom' || a.path === 'react-dom/client') return { contents: 'module.exports = window.ReactDOM', loader: 'js' }
      if (a.path === 'react/jsx-runtime' || a.path === 'react/jsx-dev-runtime') return {
        loader: 'js',
        contents: `const R = window.React
          const make = (type, props, key) => { const { children, ...rest } = props || {}; if (key !== undefined) rest.key = key
            return Array.isArray(children) ? R.createElement(type, rest, ...children) : children === undefined ? R.createElement(type, rest) : R.createElement(type, rest, children) }
          export const jsx = make, jsxs = make, jsxDEV = make, Fragment = R.Fragment`,
      }
      return { contents: 'module.exports = {}', loader: 'js' }
    })
    b.onResolve({ filter: /^@(storybook|figma)\// }, (a) => ({ path: a.path, namespace: 'empty' }))
    b.onLoad({ filter: /.*/, namespace: 'empty' }, () => ({ contents: 'module.exports = {}', loader: 'js' }))
  },
}
const result = await esbuild.build({
  entryPoints: [entry], bundle: true, write: false, outdir: join(root, 'dist/page-bundle'),
  format: 'iife', platform: 'browser', target: 'es2020', jsx: 'automatic', minify: true, legalComments: 'none',
  loader: { '.module.css': 'local-css', '.css': 'css' }, define: { 'process.env.NODE_ENV': '"production"' }, plugins: [globals], logLevel: 'warning',
})
const js = result.outputFiles.find((f) => f.path.endsWith('.js')).text
const css = (result.outputFiles.find((f) => f.path.endsWith('.css'))?.text || '') + '\n' + readFileSync(join(root, 'dist/modes.css'), 'utf8')
const miniReact = readFileSync(join(root, 'src/preview/mini-react.js'), 'utf8')
const safe = (s) => s.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--')
const title = name.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
const kebab = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const html = `<!doctype html>
<html lang="en" data-theme="${theme}" data-density="${density}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible+Next:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>html, body, #root { block-size: 100%; margin: 0; } body { background: var(--core-color-surface-page); }</style>
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<noscript>This page needs JavaScript.</noscript>
<script>${safe(miniReact)}</script>
<script>${safe(js)}</script>
</body>
</html>
`
const outDir = resolve(outArg)
mkdirSync(outDir, { recursive: true })
const out = join(outDir, `${kebab}.html`)
writeFileSync(out, html)
console.log(`Page built: ${out} (${(html.length / 1024).toFixed(0)} KB)`)
